
 CREATE TABLE user (ID INT , USER_NAME VARCHAR(50), PASSWORD_USER VARCHAR(50), PASSWORD VARCHAR(20) , ID_PHONES INT, 
 CREATED DATE , MODIFIED DATE, LAST_LOGIN DATE , TOKEN VARCHAR(250), ISACTIVE VARCHAR(1)
);

--default  CAST(FORMATDATETIME(CURRENT_TIMESTAMP(), 'yyyyMMddHHmmssSSS') as 

CREATE TABLE phones (ID_PHONES INT , NUMBER_PHONE INT , CITYCODE INT , COUNTRYCODE INT);

